site:
  title: OpenDevStack
  start_page: common:getting-started:introduction.adoc
  url: https://www.opendevstack.org/ods-documentation

content:
  sources:
    - url: https://github.com/opendevstack/opendevstack.github.io
      start_path: docs
      branches:
      - 1.0.x
      - 1.1.x
      - 1.2.x
      - master
    - url: https://github.com/opendevstack/ods-core.git
      start_path: docs
      branches:
      - 1.0.x
      - 1.1.x
      - 1.2.x
      - 2.x
      - master
    - url: https://github.com/opendevstack/ods-jenkins-shared-library.git
      start_path: docs
      branches:
      - 1.0.x
      - 1.1.x
      - 1.2.x
      - 2.x
      - master
    - url: https://github.com/opendevstack/ods-provisioning-app.git
      start_path: docs
      branches:
      - 1.0.x
      - 1.1.x
      - 1.2.x
      - 2.x
      - master
    - url: https://github.com/opendevstack/ods-project-quickstarters.git
      start_path: docs
      branches:
      - 1.1.x
      - 1.2.x
      - 2.x
    - url: https://github.com/opendevstack/ods-quickstarters.git
      start_path: docs
      branches:
      - master
      - 2.x
asciidoc:
  extensions:
    - asciidoctor-plantuml
  attributes:
    plantuml-server-url: 'http://www.plantuml.com/plantuml'
    plantuml-fetch-diagram: true

output:
  dir: ./docs
ui:
  bundle:
    url: https://github.com/opendevstack/ods-docs-ui/releases/download/v1.0.3/ui-bundle.zip
